# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=/usr/local/sbin:/usr/local/opt/inetutils/libexec/gnubin:/opt/apache-maven-3.6.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/lib/node_modules:/Users/jarod/bin:$HOME/platform-tools

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$HOME/.dotfiles/zsh/omz-custom"


# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_THEME="powerlevel10k/powerlevel10k"

# load modules
zmodload zsh/zpty

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(zsh-syntax-highlighting zsh_reload osx vscode iterm2)

##################
# External Files #
##################

source $ZSH/oh-my-zsh.sh

# User configuration

# Customise Shell
DEFAULT_USER='jarod'
PROMPT_EOL_MARK=''

# -------
# Aliases
# -------

alias py="python3"
alias weather="curl v2.wttr.in"
alias vim="nvim"
alias ovim="/usr/bin/vim"

# Filetype Aliases
alias -s txt=vim
alias -s js=node
alias -s ts=ts-node
alias -s py=python3

# Global Aliases
alias -g L="| less"
alias -g C="| pbcopy"
alias -g V="pbpaste"
alias -g G="| grep"
alias -g Ge="| grep -E"
alias -g H="| head -n"
alias -g T="| tail -n"
alias -g line="| head -n $1 | tail -n 1"

# npm
alias ns='npm_scripts'
alias nv='npm run serve'
alias nt='npm run test'
alias ni='npm install'
alias nscripts="npm_scripts"

# Spotify
alias sfy="spotify"
alias next="spotify next"
alias prev="spotify prev"
alias pause="spotify pause"
alias play="spotify play"

alias vsf="cdf && code ."

# Terminal tabbing
alias split="split_tab"
alias vsplit="vsplit_tab"

# 1password
alias opg="op get"
alias opgi="op get item"

# Todo
alias todo="todo.sh"
alias td="todo.sh"

# Prompt Clearing
PROMPT_POSITION="default" # default | bottom (Bottom will have the effect of leaving a bunch of space when you clear)

# -------
# Exports
# -------
export COWPATH=/usr/local/share/cows:~/.cows

# --------------
# Java & Android
# --------------
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home
export ANDROID_HOME=~/Library/Android/sdk
export ANDROID_SDK_ROOT=~/Library/Android/sdk

# ---------------------
# Custom Plugin Manager
# ---------------------

# Sources all files in ./plugins unless they end with .disable
for file in ~/.dotfiles/zsh/plugins/*; do
	if [ $(echo "$file" | grep -vE ".disable$") ]; then
		source "$file"
	fi
done

# -------------
# Other Plugins
# -------------

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
